[package]
name = "adiscord-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
goldilocks-json-fmt = "0.2.0"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
headless_chrome = { git = "https://github.com/atroche/rust-headless-chrome" }
serde_json = "1.0.99"
