use serde::Deserialize;

#[derive(Deserialize, Debug)]
pub enum Feature {
    AnimatedBanner(String),
    AnimatedIcon(String),
    ApplicationCommandPermissionsV2(String),
    AutoModeration(String),
    Banner(String),
    Community(String),
    CreatorMonetizableProvisional(String),
    CreatorStorePage(String),
    DeveloperSupportServer(String),
    Discoverable(String),
    Featurable(String),
    HasDirectoryEntry(String),
    Hub(String),
    InvitesDisabled(String),
    InviteSplash(String),
    LinkedToHub(String),
    MemberVerificationGateEnabled(String),
    MonetizationEnabled(String),
    MoreStickers(String),
    News(String),
    Partnered(String),
    PreviewEnabled(String),
    PrivateThreads(String),
    RelayEnabled(String),
    RoleIcons(String),
    RoleSubscriptionsAvailableForPurchase(String),
    RoleSubscriptionsEnabled(String),
    TicketedEventsEnabled(String),
    VanityURL(String),
    Verified(String),
    VIPRegions(String),
    WelcomeScreenEnabled(String),
}
